### ISSUE TITLE
了解 Scrum 是否較適用於軟體設計？

### ISSUE THREAD

**Issue by GodBlessPP** [Yen-Chung-En/2015cdb_g1#11]

**Comment by s40223237** [comment]
YES
Scrum類似框架(軟體開發過程),對外向客戶老闆,對內有活動,產生物,
  為管理軟體開發項目而開發的，也可以用於運行軟體維護團隊，
  或者作為計劃管理方法

**Comment by s40223237** [comment]
英文本: Scrum and XP from the Trenches
http://wwwis.win.tue.nl/2R690/doc/ScrumAndXpFromTheTrenchesonline07-31.pdf
中文本: Scrum 與 XP 的實戰經驗 
http://www.infoq.com/resource/news/2007/06/scrum-xp-book/en/resources/ScrumAndXpFromTheTrenchesonline_TraditionalChinese.pdf
